---
title: "Ex. 3: More ggplot2 Commands"
subtitle: "Thematic and Display Adjustments"
author: ""
output:
  xaringan::moon_reader:
    seal: TRUE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = TRUE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
employed_under_150K %>% 
  group_by(Age, 
           Sex) %>% 
  summarise(Median = median(Earnings)) %>% 
  ggplot(aes(x = Age, 
             y=Median)) +
  geom_line() +
  aes(color = Sex) +
  labs(x="Age (Years)") +
  labs(y="Earnings (USD)") +
  labs(color = "Sex of respondent") +
  labs(title = "Age vs. Median Earnings by Sex") +
  scale_x_continuous(limits=c(0,100), 
                     breaks=c(seq(from = 0,
                                  to = 100,
                                  by = 10))) +
  scale_y_continuous(limits=c(0,70000), 
                     breaks=c(10000, 30000, 50000)) +
  theme_bw() +
  theme_dark() +
  theme_light() +
  theme_gray() +
  theme_void() +
  theme_linedraw() +
  theme_minimal() +
  theme_classic()
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 90%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

