---
title: "Ex. 1.2: Data Exploration"
subtitle: "Using summarize()"
author: ""
output:
  xaringan::moon_reader:
    seal: TRUE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = TRUE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
wage_data %>%
  filter(Occupation != "53: Never Worked" & 
           Earnings > 0) %>% 
  summarise(mean(Earnings)) %>% 
  as.numeric() ->
mean_earnings

#printing saved object
mean_earnings

wage_data %>%
  filter(Occupation != "53: Never Worked" & 
           Earnings > 0) %>% 
  group_by(Sex) %>% 
  summarise(mean = mean(Earnings),
            count = n()) ->
mean_earnings_by_sex

mean_earnings_by_sex
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 90%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

